version: "3.4"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carte-jeune-engage
    ports:
      - "5433:5432"

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
