kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  PAYLOAD_CONFIG_PATH: payload/payload.config.ts
  SMTP_HOST: smtp.tipimail.com
  SMTP_PORT: "587"
  SMTP_USER: eb051b1140e9cb265a76855346fba330
  SMTP_FROM_NAME: "Carte Jeune Engagé"
  SMTP_FROM_ADDRESS: cje@fabrique.social.gouv.fr
  OBIZ_SOAP_HOST: webservices.reducce.fr
