kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  PAYLOAD_CONFIG_PATH: payload/payload.config.ts
  SMTP_FROM_NAME: "Carte Jeune Engagé"
  SMTP_FROM_ADDRESS: cje@fabrique.social.gouv.fr
