apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: cje-app-sealed-secret
  namespace: cje
spec:
  encryptedData:
    PAYLOAD_SECRET: AgCHMXWR5pWe2vE+vU9DCLhcwCck8vQ7T1Mr4KIhY8ucafM8TBc1YQQ8v4/RLZgTxJ+h54BIO2oUjMI850tzurHps8y5cBuyLGBc1ovK0bTH/TtOMnFpHe08h4I6RRKQ8+NeHMzuLvKfNGlApRWiYE2EItgJqZo75ETbU/fnD4tiuzJEX77cby6lLkx92a2NnVza5/uXhr1kIvTeuB2jf7yUqav4/AtIz9pnNlPUuR7fnZjA1ehoc0kEbN+5CtJYtpmhtSz4LKclXHuGGu6DipzngzgHoOeA+vlQCb83oTTDC3W8x1aTeZ5J9HRTqbFJMJ0dbjm4fxYe8VnSu+/FDdZYVhfSxg5yDAjNfaWOHnrVpwVzfJD3t0V3la3mbe7W5malK0zMxMnx1htg3H+6XjKW7tEv52c0WLDojKYbzf2Og5ACEEGCIuLk7Gp1FsQBpFPE2x/LPFsUSVD0qB0ccBPkauxLNBLo/YxTWYBgXVjzbsm3hM7y1KEvOZ9ftlLx26+a6G1Ibf3j3gW7AYPkGQJEOY5h0g2R562oXTWpQLafQK80H9y5vEW8hG1lko0XnOGZDIlldzuXwsuOKZS64KpBdZkwiMR0lXFcCOwwCp8T6mw3tK7vTYccdyp/bc47g4TfFX5DqcNQ3QWqTXlR3xWlBZmSFEK0pgfQE1iHXHVl+LPYo5szs7r3vlzdvlkZSXlJXiq0IMV/yXSjwM5YVrQ7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      name: cje-app-sealed-secret
    type: Opaque