app:
  annotations:
    oblik.socialgouv.io/min-request-cpu: "300m"
    oblik.socialgouv.io/min-request-memory: "768Mi"
    oblik.socialgouv.io/min-limit-cpu: "450m"
    oblik.socialgouv.io/min-limit-memory: "768Mi"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: carte-jeune-engage-dev-app-access-key

maildev: {}

jobs:
  runs:
    seed:
      ~needs: [build-app, pg]
      checkout: false
      shell: sh
      image: "{{ .Values.global.registry }}{{ if .Values.global.imageProject }}{{ print `/` .Values.global.imageProject }}{{ end }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
      run: "yarn payload migrate && yarn seed:prod"
      envFrom:
        - secretRef:
            name: pg-app
    build-app:
      with:
        buildArgs:
          NEXT_PUBLIC_JWT_NAME: cje-jwt-dev
          NEXT_PUBLIC_CRISP_TOKEN: 53f1b086-7828-49de-abb4-0c6765d9ca13
          NEXT_PUBLIC_MATOMO_TRACKING_ENABLED: "false"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_MATOMO_SITE_ID: 112
          NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: BEhweKLgZWqV1WJF6rRUaNiN-qjZPd7KlI_i3E9u2Xg_z2oPePiwgiNbIebpSTXx38epVeVxzfEDsr4atZLf4bA
