apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-notification
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 0 18 * * *
  timeZone: Europe/Paris
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: notification
              image: "{{ or .Values.registry .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
              command: ["yarn", "cron-job-notifications"]
              resources:
                requests:
                  cpu: 200m
                  memory: 2Gi
                limits:
                  cpu: 200m
                  memory: 2Gi
              {{/* workingDir: /app */}}
              env:
                - name: PRODUCTION
                  value: 'true'
                - name: NEXT_PUBLIC_ENV_APP
                  value: preproduction
                - name: NEXT_PUBLIC_URL_APP
                  value: "https://{{ .Values.global.host }}"
                - name: DATABASE_URL
                  value: "$(DATABASE_URL)"
                - name: TZ
                  value: Europe/Paris
              envFrom:
                - configMapRef:
                    name: app-configmap
                - secretRef:
                    name: pg-app
                - secretRef:
                    name: app-sealed-secret
                - secretRef:
                    name: carte-jeune-engage-dev-app-access-key