apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-notification
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: 0 18 * * *
  jobTemplate:
    {{- include "job.notification" . | nindent 4 }}
