apiVersion: batch/v1
kind: CronJob
metadata:
  name: obiz-integration-cron
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "0 4 * * *" 
  timeZone: Europe/Paris
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: obiz-integration
              image: "{{ or .Values.registry .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/app:{{ .Values.global.imageTag }}"
              command: ["python3", "importer.py"]
							args: [
                "--api-url", "$(PAYLOAD_API_URL)",
                "--api-key", "$(PAYLOAD_API_KEY)",
                "--sftp-host", "$(SFTP_HOST)",
                "--sftp-username", "$(SFTP_USERNAME)",
                "--sftp-password", "$(SFTP_PASSWORD)",
                "--sftp-path", "$(SFTP_PATH)"
              ]
							# env:
              # TOUS LES ARGS
              resources:
                requests:
                  cpu: 200m
                  memory: 2Gi
                limits:
                  cpu: 200m
                  memory: 2Gi
              volumeMounts:
                - name: inputs
                  mountPath: /app/inputs
          volumes:
            - name: inputs
              emptyDir: {}