global:
  namespace: carte-jeune-engage

jobs:
  runs:
    build-app:
      use: build
      with:
        buildArgs:
          PRODUCTION: 1
app:
  host: cje.fabrique.social.gouv.fr
  autoscale:
    minReplicas: 2
    maxReplicas: 10
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: carte-jeune-engage-prod-app-access-key
