jobs:
  runs:
    build-app:
      use: build
      with:
        buildArgs:
          PRODUCTION: 1
          NEXT_PUBLIC_ENV_APP: production
          NEXT_PUBLIC_JWT_NAME: cje-jwt-prod
          NEXT_PUBLIC_CRISP_TOKEN: e69a24b5-c98d-4ff2-9400-706f07bf8c55
          NEXT_PUBLIC_MATOMO_TRACKING_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_MATOMO_SITE_ID: 103
          NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: BEhweKLgZWqV1WJF6rRUaNiN-qjZPd7KlI_i3E9u2Xg_z2oPePiwgiNbIebpSTXx38epVeVxzfEDsr4atZLf4bA
app:
  host: cje.fabrique.social.gouv.fr
  resources:
    limits:
      cpu: 100m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  autoscale:
    enabled: true
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: carte-jeune-engage-prod-app-access-key

pg:
  cnpg-cluster:
    resources:
      requests:
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 1Gi
