global:
  host: "cje.fabrique.social.gouv.fr"
  
jobs:
  runs:
    build-app:
      use: build
      with:
        buildArgs:
          PRODUCTION: 1
          NEXT_PUBLIC_ENV_APP: production
          NEXT_PUBLIC_URL_APP: https://cje.fabrique.social.gouv.fr
          NEXT_PUBLIC_JWT_NAME: cje-jwt-prod
          NEXT_PUBLIC_CRISP_TOKEN: e69a24b5-c98d-4ff2-9400-706f07bf8c55
          NEXT_PUBLIC_MATOMO_TRACKING_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_MATOMO_SITE_ID: 103
          NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY: BEhweKLgZWqV1WJF6rRUaNiN-qjZPd7KlI_i3E9u2Xg_z2oPePiwgiNbIebpSTXx38epVeVxzfEDsr4atZLf4bA
          NEXT_PUBLIC_WIDGET_TOKEN_NAME: widget-token
app:
  host: cje.fabrique.social.gouv.fr
  autoscale:
    minReplicas: 4
    maxReplicas: 12
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 2048Mi
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: carte-jeune-engage-prod-app-access-key

pg:
  cnpg-cluster:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi
