jobs:
  runs:
    build-app:
      use: build
      with:
        buildArgs:
          PRODUCTION: 1
          NEXT_PUBLIC_JWT_NAME: cje-jwt-prod
          NEXT_PUBLIC_CRISP_TOKEN: 53f1b086-7828-49de-abb4-0c6765d9ca13
          NEXT_PUBLIC_MATOMO_TRACKING_ENABLED: "true"
          NEXT_PUBLIC_MATOMO_URL: https://matomo.fabrique.social.gouv.fr/
          NEXT_PUBLIC_MATOMO_SITE_ID: 103
app:
  host: cje.fabrique.social.gouv.fr
  autoscale:
    minReplicas: 2
    maxReplicas: 10
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap
    - secretRef:
        name: carte-jeune-engage-prod-app-access-key
