kind: ConfigMap
apiVersion: v1
metadata:
  name: app-configmap
data:
  PAYLOAD_CONFIG_PATH: payload/payload.config.ts
  SMTP_HOST: maildev
  SMTP_PORT: 1025
  SMTP_FROM_NAME: "Carte Jeune Engagé"
  SMTP_FROM_ADDRESS: cje@fabrique.social.gouv.fr
  NEXT_PUBLIC_JWT_NAME: cje-jwt
  NEXT_PUBLIC_MATOMO_TRACKING_ENABLED: "false"
