apiVersion: batch/v1
kind: CronJob
metadata:
  name: obiz-integration-cron
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  schedule: "0 4 * * *" 
  timeZone: Europe/Paris
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: obiz-integration
              image: "{{ or .Values.registry .Values.global.registry }}/{{ .Values.global.imageProject }}/{{ .Values.global.imageRepository }}/obiz:{{ .Values.global.imageTag }}"
              command: ["python3", "importer.py"]
              args: [
                "--api-url", "$(APP_API_URL)",
                "--api-key", "$(APP_API_KEY)",
                "--sftp-host", "$(SFTP_HOST)",
                "--sftp-username", "$(SFTP_USERNAME)",
                "--sftp-password", "$(SFTP_PASSWORD)",
                "--sftp-path", "$(SFTP_PATH)",
                "--sftp-port", "$(SFTP_PORT)"
              ]
              env:
                - name: APP_API_URL
                  value: "https://{{ $.Values.global.host }}/api"
              envFrom:
                - secretRef:
                  name: obiz-sealed-secret
              resources:
                requests:
                  cpu: 200m
                  memory: 2Gi
                limits:
                  cpu: 200m
                  memory: 2Gi
              volumeMounts:
                - name: inputs
                  mountPath: /app/inputs
          volumes:
            - name: inputs
              emptyDir: {}
