projectName: carte-jeune-engage
ciNamespace: ci-carte-jeune-engage

dependencies:
  fabrique:
    extends:
      - name: ovh
        ifEnv: [dev, preprod]
      - name: buildkit-service
        ifEnv: [dev, preprod]
    dependencies:
      contrib:
        preDeploy:
          importSecrets:
            options:
              secrets:
                carte-jeune-engage-dev-backups-access-key:
                carte-jeune-engage-prod-backups-access-key:
                carte-jeune-engage-dev-app-access-key:
                  env: [ dev, preprod ]
                carte-jeune-engage-prod-app-access-key:
                  env: [ prod ]
