app:
  ~chart: app
  ~needs: [build-app]
  annotations:
    oblik.socialgouv.io/min-request-cpu: "350m"
    oblik.socialgouv.io/min-request-memory: "1024Mi"
    oblik.socialgouv.io/min-limit-cpu: "500m"
    oblik.socialgouv.io/min-limit-memory: "1024Mi"
  imagePackage: app
  probesPath: /api/healthz

  env:
    - name: DATABASE_URL
      value: "$(DATABASE_URL)"

pg:
  ~chart: pg

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        context: ./webapp
        secrets:
          sentry_auth_token:
            secretName: app-sealed-secret
            secretKey: SENTRY_AUTH_TOKEN

    build-obiz-jobs:
      use: build
      with:
        imagePackage: obiz-jobs
        context: ./packages/obiz
