app:
  ~chart: app
  ~needs: [build-app, pg]
  host: "app-{{ $.Values.global.host }}"
  imagePackage: app
  containerPort: 8080
  probesPath: /api/healthz
  resources:
    requests:
      cpu: 0.3
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
  env:
    - name: DATABASE_URL
      value: "$(DATABASE_URL)"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: app-sealed-secret
    - configMapRef:
        name: app-configmap

pg:
  ~chart: pg

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
