app:
  ~chart: app
  ~needs: [build-app]
  imagePackage: app
  probesPath: /api/healthz

  env:
    - name: DATABASE_URL
      value: "$(DATABASE_URL)"

pg:
  ~chart: pg

jobs:
  runs:
    build-app:
      use: build
      with:
        imagePackage: app
        context: ./webapp
        secrets:
          sentry_auth_token:
            secretName: app-sealed-secret
            secretKey: SENTRY_AUTH_TOKEN

