cje-app:
  ~chart: cje-app
  ~needs: [build-cje-app, pg]
  host: "cje-app-{{ $.Values.global.host }}"
  imagePackage: cje-app
  containerPort: 8080
  probesPath: /_health
  resources:
    requests:
      cpu: 0.3
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi
  env:
    - name: DATABASE_URL
      value: "$(DATABASE_URL)"
  envFrom:
    - secretRef:
        name: pg-app
    - secretRef:
        name: cje-app-sealed-secret
    - secretRef:
        name: azure-cje-volume
    - configMapRef:
        name: cje-app-configmap
  volumeMounts:
    - name: uploads
      mountPath: /app/public/uploads
  volumes:
    - name: uploads
      persistentVolumeClaim:
        claimName: uploads

pg:
  ~chart: pg

jobs:
  runs:
    build-cje-app:
      use: build
      with:
        imagePackage: cje-app
