name: 📦 Release
on:
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  id-token: write  # Required for OIDC token generation
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get GitHub App Token
        id: token
        uses: SocialGouv/token-bureau@main
        with:
          token-bureau-url: https://token-bureau.fabrique.social.gouv.fr
          audience: socialgouv
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: cycjimmy/semantic-release-action@v4
        with:
          extends: |
            @socialgouv/releaserc
          working_directory: ./webapp
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
